stages:
  - build
  - test

build:
  stage: build
  image: python:3.9
  tags:
    - fit2107-runner
  script:
    - echo "Building"
    - pip install --upgrade pip
    - pip install PEP517
    - pip install backports.zoneinfo
    - pip install -r requirements.txt
    - python3 app/calculator.py
    - python3 app/calculator_form.py

test:
  stage: test
  image: python:3.9
  script:
    - echo "Testing"
    - pip install --upgrade pip
    - pip install PEP517
    - pip install backports.zoneinfo
    - pip install -r requirements.txt
    - coverage run --branch -m unittest discover -s . && coverage report