stages:
  - build
  - test

build:
  stage: build
  image: python:3.8-alpine
  tags:
    - fit2107-runner
  script:
    - echo "Building"
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install --no-use-pep517 bcrypt
    - python3 app/calculator.py
    - python3 app/calculator_form.py

test:
  stage: test
  image: python:3.8-alpine
  script:
    - echo "Testing"
    - pip install --upgrade pip
    - python3 -m unittest 