before_script:
    - pip install --upgrade pip setuptools wheel
    - pip install -r requirements.txt
stages:
  - build
  - test
build:
  stage: build
  tags:
    - fit2107-runner
  image: python:3.8-alpine
  script:
    - echo "Building"
    - pip3 install --upgrade pip
    - python3 app/calculator_form.py

test:
  stage: test
  image: python:3.8-alpine
  script:
    - echo "Testing"
    - pip3 install --upgrade pip
    - python3 -m calculator_form_test test.calculator_form_test