stages:
    - build
    - test

build:
    stage: build
    image: python:3.9-alpine
    script: 
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install --flask_wtf pip
        - python3  app/calculator_form.py

test:
    stage: test
    image: python:3.9
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 app/calculator_form.py
        - coverage app/calculator_form.py
        - coverage report
        - coverage html
