stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script: 
        - echo "Building"
        - pip3 install --upgrade pip
        - pip3 install -r requirement.txt
        - python3 -m unittest test/unittest.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 test/unittest.py
        - coverage app/calculator.py
        - coverage report
        - coverage html
