stages:
  - build
  - test

build:
  stage: build
  image: python:3.9
  tags:
    - fit2107-runner
  script:
    - echo "Building"
    - pip install --upgrade pip
    - pip install PEP517
    - pip install backports.zoneinfo
    - pip install -r requirements.txt
    - python3 app/calculator.py

test:
  stage: test
  image: python:3.8-alpine
  script:
    - echo "Testing"
    - pip install --upgrade pip
    - python3 -m unittest 
    - coverage report -m