stages:
    - build
    - test

build:
    stage: build
    image: python:3.8-alpine
    script: 
        - echo "Building"
        - pip3 install --upgrade pip
        - python3 calculator.py
         -python3 calculator_form.py

test:
    stage: test
    image: python:3.8-alpine
    script:
        - echo "Testing"
        - pip3 install --upgrade pip
        - python3 test/pyunittest.py
        - coverage app/calculator.py
        - coverage report
        - coverage html
        - coverage run app/calculator_form.py
        - coverage report
        - coverage html